from .nodes.loader_nodes import (
    NODE_CLASS_MAPPINGS as LOADER_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LOADER_DISPLAY,
)
from .nodes.generate_nodes import (
    NODE_CLASS_MAPPINGS as GENERATE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GENERATE_DISPLAY,
)
from .nodes.sam_nodes import (
    NODE_CLASS_MAPPINGS as SAM_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SAM_DISPLAY,
)
from .nodes.video_nodes import (
    NODE_CLASS_MAPPINGS as VIDEO_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_DISPLAY,
)
from .nodes.system_nodes import (
    NODE_CLASS_MAPPINGS as SYSTEM_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SYSTEM_DISPLAY,
)
from .nodes.diffusion_nodes import (
    NODE_CLASS_MAPPINGS as DIFFUSION_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as DIFFUSION_DISPLAY,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LOADER_MAPPINGS)
NODE_CLASS_MAPPINGS.update(GENERATE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SAM_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VIDEO_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SYSTEM_MAPPINGS)
NODE_CLASS_MAPPINGS.update(DIFFUSION_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LOADER_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(GENERATE_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(SAM_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(SYSTEM_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(DIFFUSION_DISPLAY)
